kind: Pod
apiVersion: v1
metadata:
  name: sidecar
  labels:
    app: nginx
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - name: busybox
    image: quay.io/choudeshell/busybox:codemash
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10;done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx