apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/mydata      
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path