---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: quay.io/choudeshell/busybox:codemash
      name: busybox
      command: [ "sh", "-c"]
      args:
      - sleep 10000
      env:
        - name: MESSAGE                                      
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: things
  restartPolicy: Never