apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleep
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleep
            image: quay.io/choudeshell/busybox:codemash
            imagePullPolicy: IfNotPresent
            command: ["date"]             
          restartPolicy: OnFailure ####