apiVersion: v1
kind: Pod
metadata:
  name: nginx-probes
  labels:
    role: web
spec:
  containers:
  - name: nginx-probes
    image: quay.io/choudeshell/nginx:codemash
    readinessProbe:
       httpGet:
            scheme: HTTP
            path: /index.html
            port: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 20