apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:  
  containers:
    - image: quay.io/choudeshell/stress-ng:codemash
      resources:
        limits:
          cpu: "2m"
        requests:
          cpu: "1m"
      name: stress
      args:
      - --cpu
      - '4' 
      - --io 
      - '2'
      - --vm
      - '1'
      - --timeout
      - 20s
      - --vm-bytes
      - '10%'
      - --vm-method
      - 'all'
      - --metrics-brief
  restartPolicy: Never