apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: quay.io/choudeshell/busybox:codemash
      name: busybox
      command: [ "sh", "-c"]
      args:
      - 'echo $MY_ENV_VAR'
      env:
        - name: 'MY_ENV_VAR'
          value: 'codemash'
  restartPolicy: Never